name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Fixed cron syntax
  workflow_dispatch:
  push:
    branches:
      - main  # Change to 'main' if that's your default branch

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3  # Add checkout step
      
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: azraihan  # Use your actual username
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}